### ISSUE TITLE
Implement dynamic movement bounds

### ISSUE THREAD

**Issue by hybridherbst** [prefrontalcortex/DomeTools#14]
Currently, when walking around, teleporting, or switching to a smaller Dome layout, the user can leave the dome.
A related issue is that when switching from 1:1 view to miniature view, the user ends up too far away from the dome model.

**Comment by Tunkali** [comment]
For normal mode this fix is working. Miniature Mode is still todo:

https://github.com/prefrontalcortex/DomeTools/pull/23

**Comment by hybridherbst** [comment]
Thanks! I don't think miniature mode needs that at the moment.
