### ISSUE TITLE
Add gaze- or hands-based movement

### ISSUE THREAD

**Issue by hybridherbst** [prefrontalcortex/DomeTools#19]
**VRC.Content.2** from Quest Store:
Users must be able to move while using hand tracking when hand tracking is listed as supported input device.

**Comment by Tunkali** [comment]
is fixed here https://github.com/prefrontalcortex/DomeTools/pull/24

And is also accepted by meta.

**Comment by hybridherbst** [comment]
Let's stick with hands for now!
