### ISSUE TITLE
Prevent falling off the map

### ISSUE THREAD

**Issue by hybridherbst** [prefrontalcortex/DomeTools#20]
Feedback:
> If the user walks outside of the dome, they can fall of the map with no way to return.

I'm not aware of even having any "falling" functionality though...

**Comment by Tunkali** [comment]
Can not reproduce. I guess the testuser just lost orientation because of no bounds? At farclipping point still no falling.

**Comment by hybridherbst** [comment]
Should be fixed by https://github.com/prefrontalcortex/DomeTools/pull/23
